package notion

// Code generated by notion.doc2api; DO NOT EDIT.
func getTypeForBinding(p Property) string {
	switch p.Type {
	case "title":
		return "[]RichText"
	case "rich_text":
		return "[]RichText"
	case "number":
		return "nullv4.Float"
	case "select":
		return "*Option"
	case "status":
		return "Option"
	case "multi_select":
		return "[]Option"
	case "date":
		return "*DatePropertyValueData"
	case "formula":
		return "Formula"
	case "relation":
		return "[]PageReference"
	case "rollup":
		return "Rollup"
	case "people":
		return "[]User"
	case "files":
		return "[]File"
	case "checkbox":
		return "bool"
	case "url":
		return "nullv4.String"
	case "email":
		return "nullv4.String"
	case "phone_number":
		return "nullv4.String"
	case "created_time":
		return "ISO8601String"
	case "created_by":
		return "User"
	case "last_edited_time":
		return "ISO8601String"
	case "last_edited_by":
		return "User"
	}
	panic(p)
}
