// Code generated by notion.doc2api; DO NOT EDIT.
// https://developers.notion.com/reference/delete-a-block

package notion

import (
	"context"
	"fmt"
	uuid "github.com/google/uuid"
	"net/http"
)

/*
Sets a [Block object](ref:block), including page blocks, to `archived: true` using the ID specified. Note: in the Notion UI application, this moves the block to the "Trash" where it can still be accessed and restored.

To restore the block with the API, use the [Update a block](ref:update-a-block) or [Update page](ref:patch-page) respectively.

> 📘 Integration capabilities
>
> This endpoint requires an integration to have update content capabilities. Attempting to call this API without update content capabilities will return an HTTP response with a 403 status code. For more information on integration capabilities, see the [capabilities guide](ref:capabilities).

### Errors

Returns a 404 HTTP response if the block doesn't exist, or if the integration doesn't have access to the block.

Returns a 400 or 429 HTTP response if the request exceeds the [request limits](ref:request-limits).

_Note: Each Public API endpoint can return several possible error codes. See the [Error codes section](https://developers.notion.com/reference/status-codes#error-codes) of the Status codes documentation for more information._
*/
func (c *Client) DeleteBlock(ctx context.Context, block_id uuid.UUID, options ...callOption) (*Block, error) {
	return call(
		ctx,
		c.accessToken,
		http.MethodDelete,
		fmt.Sprintf("/v1/blocks/%v", block_id),
		nil,
		accessValue[*Block],
		options...,
	)
}
