// Code generated by notion.doc2api; DO NOT EDIT.
// https://developers.notion.com/reference/post-database-query

package notion

import (
	"context"
	"fmt"
	uuid "github.com/google/uuid"
	"net/http"
)

/*
Gets a list of [Pages](ref:page) and/or [Databases](https://developers.notion.com/reference/database) contained in the database, filtered and ordered according to the filter conditions and sort criteria provided in the request. The response may contain fewer than `page_size` of results. If the response includes a `next_cursor` value, refer to the [pagination reference](https://developers.notion.com/reference/intro#pagination) for details about how to use a cursor to iterate through the list.

> 📘
>
> [Wiki](https://www.notion.so/help/wikis-and-verified-pages) databases can contain both pages and databases as children.

[**Filters**](ref:post-database-query-filter) are similar to the [filters provided in the Notion UI](https://www.notion.so/help/views-filters-and-sorts) where the set of filters and filter groups chained by "And" in the UI is equivalent to having each filter in the array of the compound `"and"` filter. Similar a set of filters chained by "Or" in the UI would be represented as filters in the array of the `"or"` compound filter.
Filters operate on database properties and can be combined. If no filter is provided, all the pages in the database will be returned with pagination.

[block:image]

	{
	  "images": [
	    {
	      "image": [
	        "https://files.readme.io/6fe4a44-Screen_Shot_2021-12-23_at_11.46.21_AM.png",
	        "Screen Shot 2021-12-23 at 11.46.21 AM.png",
	        1340
	      ],
	      "align": "center",
	      "caption": "The above filters in the UI can be represented as the following filter object"
	    }
	  ]
	}

[/block]

```json Filter Object

	{
	  "and": [
	    {
	      "property": "Done",
	      "checkbox": {
	        "equals": true
	      }
	    },
	    {
	      "or": [
	        {
	          "property": "Tags",
	          "contains": "A"
	        },
	        {
	          "property": "Tags",
	          "contains": "B"
	        }
	      ]
	  	}
	  ]
	}

```

In addition to chained filters, databases can be queried with single filters.

```json

	{
	    "property": "Done",
	    "checkbox": {
	        "equals": true
	   }
	 }

```

[**Sorts**](ref:post-database-query-sort) are similar to the [sorts provided in the Notion UI](https://notion.so/notion/Intro-to-databases-fd8cd2d212f74c50954c11086d85997e#0eb303043b1742468e5aff2f3f670505). Sorts operate on database properties or page timestamps and can be combined. The order of the sorts in the request matter, with earlier sorts taking precedence over later ones.

The properties of the database schema returned in the response body can be filtered with the `filter_properties` query parameter.

```
https://api.notion.com/v1/databases/[database_id]/query?filter_properties=[property_id_1]
```

Multiple filter properties can be provided by chaining the `filter_properties` query param.

```
https://api.notion.com/v1/databases/[database_id]/query?filter_properties=[property_id_1]&filter_properties=[property_id_2]
```

Property IDs can be determined with the [Retrieve a database](https://developers.notion.com/reference/retrieve-a-database) endpoint.

If you are using the [Notion JavaScript SDK](https://github.com/makenotion/notion-sdk-js), the `filter_properties` endpoint expects an array of property ID strings.

```javascript

	notion.databases.query({
		database_id: id,
		filter_properties: ["propertyID1", "propertyID2"]
	})

```

> 📘 Permissions
>
> Before an integration can query a database, the database must be shared with the integration. Attempting to query a database that has not been shared will return an HTTP response with a 404 status code.
>
> To share a database with an integration, click the ••• menu at the top right of a database page, scroll to `Add connections`, and use the search bar to find and select the integration from the dropdown list.

> 📘 Integration capabilities
>
> This endpoint requires an integration to have read content capabilities. Attempting to call this API without read content capabilities will return an HTTP response with a 403 status code. For more information on integration capabilities, see the [capabilities guide](ref:capabilities).

> 📘 To display the page titles of related pages rather than just the ID:
>
> 1. Add a rollup property to the database which uses a formula to get the related page's title. This works well if you have access to updating the database's schema.
>
> 2. Otherwise, [retrieve the individual related pages](https://developers.notion.com/reference/retrieve-a-page) using each page ID.

> 🚧 Formula Limitation
>
> If a formula depends on a page property that is a relation, and that relation has more than 25 references, only 25 will be evaluated as part of the formula.

### Errors

Returns a 404 HTTP response if the database doesn't exist, or if the integration doesn't have access to the database.

Returns a 400 or a 429 HTTP response if the request exceeds the [request limits](ref:request-limits).

_Note: Each Public API endpoint can return several possible error codes. See the [Error codes section](https://developers.notion.com/reference/status-codes#error-codes) of the Status codes documentation for more information._
*/
func (c *Client) QueryDatabase(ctx context.Context, database_id uuid.UUID, params QueryDatabaseParams, options ...CallOption) (*Pagination[Page], error) {
	return call(
		ctx,
		c.accessToken,
		http.MethodPost,
		fmt.Sprintf("/v1/databases/%v/query", database_id),
		params,
		accessValue[*Pagination[Page]],
		options...,
	)
}

type QueryDatabaseParams map[string]any

// When supplied, limits which pages are returned based on the [filter conditions](ref:post-database-query-filter).
func (p QueryDatabaseParams) Filter(filter Filter) QueryDatabaseParams {
	p["filter"] = filter
	return p
}

// When supplied, orders the results based on the provided [sort criteria](ref:post-database-query-sort).
func (p QueryDatabaseParams) Sorts(sorts []Sort) QueryDatabaseParams {
	p["sorts"] = sorts
	return p
}

// When supplied, returns a page of results starting after the cursor provided. If not supplied, this endpoint will return the first page of results.
func (p QueryDatabaseParams) StartCursor(start_cursor string) QueryDatabaseParams {
	p["start_cursor"] = start_cursor
	return p
}

// The number of items from the full list desired in the response. Maximum: 100
func (p QueryDatabaseParams) PageSize(page_size int) QueryDatabaseParams {
	p["page_size"] = page_size
	return p
}
