// Code generated by notion.doc2api; DO NOT EDIT.

package notion

import (
	"context"
	"fmt"
	uuid "github.com/google/uuid"
	"net/http"
)

// Retrieve block children
// https://developers.notion.com/reference/get-block-children
func (c *Client) RetrieveBlockChildren(ctx context.Context, block_id uuid.UUID, options ...callOption) (*Pagination, error) {
	co := &callOptions{
		accessToken: c.accessToken,
		method:      http.MethodGet,
		params:      nil,
		path:        fmt.Sprintf("/v1/blocks/%v/children", block_id),
	}
	for _, o := range options {
		o(co)
	}
	return call(ctx, co, func(u *Pagination) *Pagination {
		return u
	})
}
