// Code generated by notion.doc2api; DO NOT EDIT.

package notion

import (
	"context"
	"fmt"
	uuid "github.com/google/uuid"
	"net/http"
)

// Retrieve a page
// https://developers.notion.com/reference/retrieve-a-page
func (c *Client) RetrievePage(ctx context.Context, page_id uuid.UUID, options ...callOption) (*Page, error) {
	co := &callOptions{
		accessToken: c.accessToken,
		method:      http.MethodGet,
		params:      nil,
		path:        fmt.Sprintf("/v1/pages/%v", page_id),
	}
	for _, o := range options {
		o(co)
	}
	return call(ctx, co, func(u *Page) *Page {
		return u
	})
}
