package notion

import (
	"encoding/json"
	"fmt"
	uuid "github.com/google/uuid"
)

// Code generated by notion.doc2api; DO NOT EDIT.
// https://developers.notion.com/reference/property-item-object

/*
A property_item object describes the identifier, type, and value of a page property. It's returned from the Retrieve a page property item
*/
type PropertyItem interface {
	isPropertyItem()
	isPropertyItemOrPropertyItemPagination()
	GetObject() alwaysPropertyItem
	GetId() string
}

/*

Each page property item object contains the following keys. In addition, it will contain a key corresponding with the value of type. The value is an object containing type-specific data. The type-specific data are described in the sections below.
*/
type propertyItemCommon struct {
	Object alwaysPropertyItem `json:"object"` // Always "property_item".
	Id     string             `json:"id"`     // Underlying identifier for the property. This identifier is guaranteed to remain constant when the property name changes. It may be a UUID, but is often a short random string.  The id may be used in place of name when creating or updating pages.
}

func (c *propertyItemCommon) GetObject() alwaysPropertyItem {
	return c.Object
}
func (c *propertyItemCommon) GetId() string {
	return c.Id
}

type propertyItemUnmarshaler struct {
	value PropertyItem
}

/*
UnmarshalJSON unmarshals a JSON message and sets the value field to the appropriate instance
according to the "type" field of the message.
*/
func (u *propertyItemUnmarshaler) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		u.value = nil
		return nil
	}
	switch string(getType(data)) {
	case "\"title\"":
		u.value = &TitlePropertyItem{}
	case "\"rich_text\"":
		u.value = &RichTextPropertyItem{}
	case "\"number\"":
		u.value = &NumberPropertyItem{}
	case "\"select\"":
		u.value = &SelectPropertyItem{}
	case "\"multi_select\"":
		u.value = &MultiSelectPropertyItem{}
	case "\"date\"":
		u.value = &DatePropertyItem{}
	case "\"formula\"":
		u.value = &FormulaPropertyItem{}
	case "\"relation\"":
		u.value = &RelationPropertyItem{}
	case "\"rollup\"":
		u.value = &RollupPropertyItem{}
	case "\"people\"":
		u.value = &PeoplePropertyItem{}
	case "\"files\"":
		u.value = &FilesPropertyItem{}
	case "\"checkbox\"":
		u.value = &CheckboxPropertyItem{}
	case "\"url\"":
		u.value = &UrlPropertyItem{}
	case "\"email\"":
		u.value = &EmailPropertyItem{}
	case "\"phone_number\"":
		u.value = &PhoneNumberPropertyItem{}
	case "\"created_time\"":
		u.value = &CreatedTimePropertyItem{}
	case "\"created_by\"":
		u.value = &CreatedByPropertyItem{}
	case "\"last_edited_time\"":
		u.value = &LastEditedTimePropertyItem{}
	case "\"last_edited_by\"":
		u.value = &LastEditedByPropertyItem{}
	default:
		return fmt.Errorf("unmarshaling PropertyItem: data has unknown type field: %s", string(data))
	}
	return json.Unmarshal(data, u.value)
}

func (u *propertyItemUnmarshaler) MarshalJSON() ([]byte, error) {
	return json.Marshal(u.value)
}

type PropertyItems []PropertyItem

func (a *PropertyItems) UnmarshalJSON(data []byte) error {
	t := []propertyItemUnmarshaler{}
	if err := json.Unmarshal(data, &t); err != nil {
		return fmt.Errorf("unmarshaling PropertyItems: %w", err)
	}
	*a = make([]PropertyItem, len(t))
	for i, u := range t {
		(*a)[i] = u.value
	}
	return nil
}

// A property_item object that describes the property.
type PaginatedPropertyInfo struct {
	Id      string   `json:"id"`
	Type    string   `json:"type"`
	Title   struct{} `json:"title,omitempty"`
	NextUrl *string  `json:"next_url"` // The URL the user can request to get the next page of results.
}

// Title property values
type TitlePropertyItem struct {
	propertyItemCommon
	Type  alwaysTitle `json:"type"`
	Title RichText    `json:"title"` //  Title property value objects contain an array of rich text objects within the title property.
}

func (_ *TitlePropertyItem) isPropertyItem()                         {}
func (_ *TitlePropertyItem) isPropertyItemOrPropertyItemPagination() {}
func (o *TitlePropertyItem) UnmarshalJSON(data []byte) error {
	type Alias TitlePropertyItem
	t := &struct {
		*Alias
		Title richTextUnmarshaler `json:"title"`
	}{Alias: (*Alias)(o)}
	if err := json.Unmarshal(data, t); err != nil {
		return fmt.Errorf("unmarshaling TitlePropertyItem: %w", err)
	}
	o.Title = t.Title.value
	return nil
}

// Rich Text property values
type RichTextPropertyItem struct {
	propertyItemCommon
	Type     alwaysRichText `json:"type"`
	RichText RichText       `json:"rich_text"` //  Rich Text property value objects contain an array of rich text objects within the rich_text property.
}

func (_ *RichTextPropertyItem) isPropertyItem()                         {}
func (_ *RichTextPropertyItem) isPropertyItemOrPropertyItemPagination() {}
func (o *RichTextPropertyItem) UnmarshalJSON(data []byte) error {
	type Alias RichTextPropertyItem
	t := &struct {
		*Alias
		RichText richTextUnmarshaler `json:"rich_text"`
	}{Alias: (*Alias)(o)}
	if err := json.Unmarshal(data, t); err != nil {
		return fmt.Errorf("unmarshaling RichTextPropertyItem: %w", err)
	}
	o.RichText = t.RichText.value
	return nil
}

// Number property values
type NumberPropertyItem struct {
	propertyItemCommon
	Type   alwaysNumber `json:"type"`
	Number float64      `json:"number"` //  Number property value objects contain a number within the number property.
}

func (_ *NumberPropertyItem) isPropertyItem()                         {}
func (_ *NumberPropertyItem) isPropertyItemOrPropertyItemPagination() {}

// Select property values
type SelectPropertyItem struct {
	propertyItemCommon
	Type   alwaysSelect           `json:"type"`
	Select SelectPropertyItemData `json:"select"` //  Select property value objects contain the following data within the select property:
}

func (_ *SelectPropertyItem) isPropertyItem()                         {}
func (_ *SelectPropertyItem) isPropertyItemOrPropertyItemPagination() {}

/*

Select property value objects contain the following data within the select property:
*/
type SelectPropertyItemData struct {
	Id    uuid.UUID `json:"id"`    // ID of the option.  When updating a select property, you can use either name or id.
	Name  string    `json:"name"`  // Name of the option as it appears in Notion.  If the select database property does not yet have an option by that name, it will be added to the database schema if the integration also has write access to the parent database.  Note: Commas (",") are not valid for select values.
	Color string    `json:"color"` // Color of the option. Possible values are: "default", "gray", "brown", "red", "orange", "yellow", "green", "blue", "purple", "pink". Defaults to "default".  Not currently editable.
}

// Multi-select property values
type MultiSelectPropertyItem struct {
	propertyItemCommon
	Type        alwaysMultiSelect             `json:"type"`
	MultiSelect []MultiSelectPropertyItemData `json:"multi_select"` //  Multi-select property value objects contain an array of multi-select option values within the multi_select property.
}

func (_ *MultiSelectPropertyItem) isPropertyItem()                         {}
func (_ *MultiSelectPropertyItem) isPropertyItemOrPropertyItemPagination() {}

/*

Multi-select property value objects contain an array of multi-select option values within the multi_select property.
*/
type MultiSelectPropertyItemData struct {
	Id    uuid.UUID `json:"id"`    // ID of the option.  When updating a multi-select property, you can use either name or id.
	Name  string    `json:"name"`  // Name of the option as it appears in Notion.  If the multi-select database property does not yet have an option by that name, it will be added to the database schema if the integration also has write access to the parent database.  Note: Commas (",") are not valid for select values.
	Color string    `json:"color"` // Color of the option. Possible values are: "default", "gray", "brown", "red", "orange", "yellow", "green", "blue", "purple", "pink". Defaults to "default".  Not currently editable.
}

// Date property values
type DatePropertyItem struct {
	propertyItemCommon
	Type alwaysDate           `json:"type"`
	Date DatePropertyItemData `json:"date"` //  Date property value objects contain the following data within the date property:
}

func (_ *DatePropertyItem) isPropertyItem()                         {}
func (_ *DatePropertyItem) isPropertyItemOrPropertyItemPagination() {}

/*

Date property value objects contain the following data within the date property:
*/
type DatePropertyItemData struct {
	Start    ISO8601String `json:"start"`     // An ISO 8601 format date, with optional time.
	End      ISO8601String `json:"end"`       // An ISO 8601 formatted date, with optional time. Represents the end of a date range.  If null, this property's date value is not a range.
	TimeZone string        `json:"time_zone"` // Time zone information for start and end. Possible values are extracted from the IANA database and they are based on the time zones from Moment.js.  When time zone is provided, start and end should not have any UTC offset. In addition, when time zone  is provided, start and end cannot be dates without time information.  If null, time zone information will be contained in UTC offsets in start and end.
}

// Formula property values
type FormulaPropertyItem struct {
	propertyItemCommon
	Type    alwaysFormula `json:"type"`
	Formula Formula       `json:"formula"` //  Formula property value objects represent the result of evaluating a formula described in the  database's properties. These objects contain a type key and a key corresponding with the value of type. The value is an object containing type-specific data. The type-specific data are described in the sections below.
}

func (_ *FormulaPropertyItem) isPropertyItem()                         {}
func (_ *FormulaPropertyItem) isPropertyItemOrPropertyItemPagination() {}

// Relation property values
type RelationPropertyItem struct {
	propertyItemCommon
	Type     alwaysRelation  `json:"type"`
	Relation []PageReference `json:"relation"` //  Relation property value objects contain an array of relation property items with page references within the relation property. A page reference is an object with an id property which is a string value (UUIDv4) corresponding to a page ID in another database.
}

func (_ *RelationPropertyItem) isPropertyItem()                         {}
func (_ *RelationPropertyItem) isPropertyItemOrPropertyItemPagination() {}

// Rollup property values
type RollupPropertyItem struct {
	propertyItemCommon
	Type   alwaysRollup `json:"type"`
	Rollup Rollup       `json:"rollup"` //  Rollup property value objects represent the result of evaluating a rollup described in the  database's properties. The property is returned as a list object of type property_item with a list of relation items used to computed the rollup under results.   A rollup property item is also returned under the property_type key that describes the rollup aggregation and computed result.   In order to avoid timeouts, if the rollup has a with a large number of aggregations or properties the endpoint returns a next_cursor value that is used to determinate the aggregation value so far for the subset of relations that have been paginated through.   Once has_more is false, then the final rollup value is returned.  See the Pagination documentation for more information on pagination in the Notion API.   Computing the values of following aggregations are not supported. Instead the endpoint returns a list of property_item objects for the rollup: * show_unique (Show unique values) * unique (Count unique values) * median(Median)
}

func (_ *RollupPropertyItem) isPropertyItem()                         {}
func (_ *RollupPropertyItem) isPropertyItemOrPropertyItemPagination() {}

// People property values
type PeoplePropertyItem struct {
	propertyItemCommon
	Type alwaysPeople `json:"type"`
}

func (_ *PeoplePropertyItem) isPropertyItem()                         {}
func (_ *PeoplePropertyItem) isPropertyItemOrPropertyItemPagination() {}

// Files property values
type FilesPropertyItem struct {
	propertyItemCommon
	Type alwaysFiles `json:"type"`
}

func (_ *FilesPropertyItem) isPropertyItem()                         {}
func (_ *FilesPropertyItem) isPropertyItemOrPropertyItemPagination() {}

// Checkbox property values
type CheckboxPropertyItem struct {
	propertyItemCommon
	Type alwaysCheckbox `json:"type"`
}

func (_ *CheckboxPropertyItem) isPropertyItem()                         {}
func (_ *CheckboxPropertyItem) isPropertyItemOrPropertyItemPagination() {}

// URL property values
type UrlPropertyItem struct {
	propertyItemCommon
	Type alwaysUrl `json:"type"`
}

func (_ *UrlPropertyItem) isPropertyItem()                         {}
func (_ *UrlPropertyItem) isPropertyItemOrPropertyItemPagination() {}

// Email property values
type EmailPropertyItem struct {
	propertyItemCommon
	Type alwaysEmail `json:"type"`
}

func (_ *EmailPropertyItem) isPropertyItem()                         {}
func (_ *EmailPropertyItem) isPropertyItemOrPropertyItemPagination() {}

// Phone number property values
type PhoneNumberPropertyItem struct {
	propertyItemCommon
	Type alwaysPhoneNumber `json:"type"`
}

func (_ *PhoneNumberPropertyItem) isPropertyItem()                         {}
func (_ *PhoneNumberPropertyItem) isPropertyItemOrPropertyItemPagination() {}

// Created time property values
type CreatedTimePropertyItem struct {
	propertyItemCommon
	Type alwaysCreatedTime `json:"type"`
}

func (_ *CreatedTimePropertyItem) isPropertyItem()                         {}
func (_ *CreatedTimePropertyItem) isPropertyItemOrPropertyItemPagination() {}

// Created by property values
type CreatedByPropertyItem struct {
	propertyItemCommon
	Type alwaysCreatedBy `json:"type"`
}

func (_ *CreatedByPropertyItem) isPropertyItem()                         {}
func (_ *CreatedByPropertyItem) isPropertyItemOrPropertyItemPagination() {}

// Last edited time property values
type LastEditedTimePropertyItem struct {
	propertyItemCommon
	Type alwaysLastEditedTime `json:"type"`
}

func (_ *LastEditedTimePropertyItem) isPropertyItem()                         {}
func (_ *LastEditedTimePropertyItem) isPropertyItemOrPropertyItemPagination() {}

// Last edited by property values
type LastEditedByPropertyItem struct {
	propertyItemCommon
	Type alwaysLastEditedBy `json:"type"`
}

func (_ *LastEditedByPropertyItem) isPropertyItem()                         {}
func (_ *LastEditedByPropertyItem) isPropertyItemOrPropertyItemPagination() {}
