package notion

import (
	"encoding/json"
	"fmt"
	"testing"
)

// Code generated by notion.doc2api; DO NOT EDIT.
// https://developers.notion.com/reference/post-database-query-sort

func TestSort_unmarshal(t *testing.T) {
	tests := []string{
		"{\n            \"property\": \"Name\",\n            \"direction\": \"ascending\"\n        }",
		"{\n            \"property\": \"Food group\",\n            \"direction\": \"descending\"\n        }",
		"{\n            \"property\": \"Name\",\n            \"direction\": \"ascending\"\n        }",
	}
	for _, wantStr := range tests {
		target := &Sort{}
		want := []byte(wantStr)
		if err := json.Unmarshal(want, target); err != nil {
			t.Fatal(fmt.Errorf("%w : %s", err, wantStr))
		}
		got, _ := json.Marshal(target)
		if want, got, ok := compareJSON(want, got); !ok {
			t.Fatal(fmt.Errorf("mismatch:\nwant: %s\ngot : %s", want, got))
		}
	}
}
