// Code generated by notion.doc2api; DO NOT EDIT.

package notion

import "testing"

// https://developers.notion.com/reference/post-database-query-sort

func TestSort_unmarshal(t *testing.T) {
	tests := []string{
		"{\n            \"property\": \"Name\",\n            \"direction\": \"ascending\"\n        }",
		"{\n            \"property\": \"Food group\",\n            \"direction\": \"descending\"\n        }",
		"{\n            \"property\": \"Name\",\n            \"direction\": \"ascending\"\n        }",
	}
	for _, wantStr := range tests {
		if err := checkUnmarshal[Sort](wantStr); err != nil {
			t.Error(err)
		}
	}
}
