package notion

import (
	"encoding/json"
	"fmt"
)

// Code generated by notion.doc2api; DO NOT EDIT.

//
type FileOrEmoji interface {
	isFileOrEmoji()
}
type fileOrEmojiCommon struct{}

func (_ *Emoji) isFileOrEmoji()            {}
func (_ *ExternalFile) isFileOrEmoji()     {}
func (_ *NotionHostedFile) isFileOrEmoji() {}

type fileOrEmojiUnmarshaler struct {
	value FileOrEmoji
}

func (u *fileOrEmojiUnmarshaler) UnmarshalJSON(data []byte) error {
	switch string(getRawProperty(data, "type")) {
	case "\"emoji\"":
		u.value = &Emoji{}
	case "\"external\"":
		u.value = &ExternalFile{}
	case "\"file\"":
		u.value = &NotionHostedFile{}
	default:
		return fmt.Errorf("unknown type: %s", string(data))
	}
	return json.Unmarshal(data, u.value)
}
